import { ERROR_CODE } from "commons/helpers/error";

export const ENABLE_WRITE_LOG = process.env.ENABLE_WRITE_LOG_CLIENT;
export const API_DOMAIN = process.env.API_DOMAIN_CLIENT;
export const PARTNER_ID = process.env.PARTNER_ID_CLIENT;
export const KEY_CHECK_SUM = process.env.KEY_CHECK_SUM_CLIENT;
export const CHANNEL_HDBS = process.env.CHANNEL_HDBS_CLIENT;
export const TOKEN_USERNAME = process.env.TOKEN_USERNAME_CLIENT;
export const TOKEN_PASSWORD = process.env.TOKEN_PASSWORD_CLIENT;
export const SECRET_KEY_ACCESS_TOKEN = process.env.SECRET_KEY_ACCESS_TOKEN;


export const API_DOMAIN_SBH_SANDBOX = process.env.API_DOMAIN_SANDBOX_SBH_CLIENT;
export const SERVICE_CODE_HDBS = process.env.SERVICE_CODE_CLIENT;
export const NARRATIVE_HDBS = process.env.NARRATIVE_CLIENT;
export const IS_REQ_CHAL_CODE_HDBS = process.env.IS_REQ_CHAL_CODE_CLIENT;
export const LANGUAGE = {
  VI: "vn",
  EN: "en",
};

export const KEY_TOKEN = "HDBS_TOKEN";
export const KEY_DATA = "HDBS_APP_DATA";

export const ERROR_MESSAGE_TIMEOUT = "Dịch vụ đang nâng cấp. Quý khách vui lòng thực hiện lại sau ít phút!";


export const ERROR_CODE_OTP_MESSAGE = {
  [LANGUAGE.VI]: {
    "20": "Phương thức xác thực của Quý khách đã bị khóa do không xác nhận quá số lần quy định. Quý khách vui lòng liên hệ tổng đài 19006060 để được hỗ trợ",
    "23": "Quý khách chưa đăng ký phương thức xác thực hoặc đã bị khóa. Quý khách vui lòng liên hệ tổng đài 19006060 để được hỗ trợ",
    "08": "Mã xác thực không đúng",
    "19": "Phương thức xác thực của Quý khách đã bị khóa do nhập sai mật khẩu quá số lần quy định. Quý khách vui lòng liên hệ tổng đài 19006060 để được hỗ trợ",
    "22": "Phương thức xác thực của Quý khách đã bị khóa do nhập sai mật khẩu quá số lần quy định. Quý khách vui lòng liên hệ tổng đài 19006060 để được hỗ trợ",
  },
  [LANGUAGE.EN]: {
    "20": "Your authentication method has been blocked due to not confirming more than the specified number of times. Please contact hotline 19006060 for support",
    "23": "Please contact hotline 19006060 for support",
    "08": "The verification code is not correct",
    "19": "Your authentication method has been blocked due to entering the wrong password more than the specified number of times. Please contact hotline 19006060 for support",
    "22": "Your authentication method has been blocked due to entering the wrong password more than the specified number of times. Please contact hotline 19006060 for support",
  },
};

export const ERROR_CODE_WITH_MESSAGE = {
  [LANGUAGE.VI]: {
    "00": "Thành công",
    "01": "PartnerId không tìm thấy",
    "02": "Merchant không tìm thấy",
    "03": "Terminal không tìm thấy",
    "04": "User eKYC không tìm thấy",
    "05": "Private key không tìm thấy",
    "06": "Ekyc user đã tồn tại",
    "07": "Register eKyc user thất bại",
    "08": "Quý khách đã mở TKCK tại Công ty chứng khoán HDB. Quý khách vui lòng chọn Công ty Chứng khoán khác!",
    "09": "Account otp không khớp",
    "10": "Ekyc account không tìm thấy",
    "11": "Thông tin CMND/CCCD khác với thông tin trên hệ thống",
    "99": "System error",
    "98": "RequestId bắt buộc",
    "97": "Channel bắt buộc",
    "96": "Language bắt buộc",
    "95": "Transaction time bắt buộc",
    "94": "PartnerId bắt buộc",
    "93": "Checksum bắt buộc",
    "92": "Không hợp lệ transaction time",
    "91": "Không hợp lệ checksum",
    "90": "Không thể lấy merchant",
    "89": "UserId bắt buộc",
    "88": "Client no bắt buộc",
    "87": "MerchantId bắt buộc",
    "86": "TerminalId bắt buộc",
    "85": "Esb check user ekyc thất bại",
    "84": "Esb Insert ekyc account thất bại",
    "83": "Account otp bắt buộc",
    "82": "Esb confirm ekyc present thất bại",
    "81": "HDBS register user thất bại",
    "80": "Esb Update ekyc account thất bại",
    "79": "Token bắt buộc",
    "78": "Username bắt buộc",
    "77": "Password bắt buộc",
    "76": "Username or password incorrect",
    "75": "Ekyc type bắt buộc",
    "74": "Không hợp lệ ekyc type",
    "73": "Email bắt buộc",
    "72": "Account no bắt buộc",
    "71": "Phone number bắt buộc",
    "70": "Full name bắt buộc",
    "69": "Không đọc được ngày sinh. Vui lòng thử lại",
    "68": "Full name ocr bắt buộc",
    "67": "Birth day ocr bắt buộc",
    "66": "Không đọc được ngày sinh. Vui lòng thử lại",
    "65": "Không đọc được ngày sinh. Vui lòng thử lại",
    "64": "Place of issue bắt buộc",
    "63": "Place of issue ocr bắt buộc",
    "62": "Expired of issue bắt buộc",
    "61": "Expired of issue ocr bắt buộc",
    "60": "Không đọc được giới tính. Vui lòng thử lại",
    "59": "Không đọc được địa chỉ. Vui lòng thử lại",
    "58": "Không đọc được địa chỉ. Vui lòng thử lại",
    "57": "Không đọc được quốc tịch. Vui lòng thử lại",
    "56": "Branch bắt buộc",
    "55": "Marital status bắt buộc",
    "54": "Face matching bắt buộc",
    "53": "Id number bắt buộc",
    "52": "Id number type bắt buộc",
    "51": "Esb inquiry ekyc present thất bại",
    "50": "Phương thức không hợp lệ",
    "49": "Yêu cầu không hợp lệ",
    "41": "Ngày phát hành không hợp lệ",
    "36": "Kiểm tra tài khoản HDBS không thành công",
    "37": "Tạo tài khoản HDBS không thành công",
    "38": "Ngày hết hạn của cmnd/cccd không hợp lệ",
    "39": "Ngày hết hạn của cmnd/cccd không hợp lệ",
    "40": "Ngày phát hành cmnd/cccd không hợp lệ",
    isUserImoney:
      "Tài khoản của quý khách chưa sử dụng được chức năng. Quý khách vui lòng đến quầy giao dịch để nâng cấp tài khoản",
    userDontEnoughAccount:
      "Quý khách vui lòng mở tài khoản thanh toán trực tuyến hoặc đến quầy giao dịch để đăng ký sử dụng dịch vụ",
  },
  [LANGUAGE.EN]: {
    "00": "Success",
    "01": "PartnerId not found",
    "02": "Merchant not found",
    "03": "Terminal not found",
    "04": "User eKYC not found",
    "05": "Private key not found",
    "06": "Ekyc user already exists",
    "07": "Register eKyc user failed",
    "08": "You have opened a securities account at HDB Securities Company. Please choose another Securities Company!”",
    "09": "Account otp not match",
    "10": "Ekyc account not found",
    "11": "Thông tin CMND/CCCD khác với thông tin trên hệ thống",
    "99": "System error",
    "98": "RequestId is required",
    "97": "Channel is required",
    "96": "Language is required",
    "95": "Transaction time is required",
    "94": "PartnerId is required",
    "93": "Checksum is required",
    "92": "Invalid transaction time",
    "91": "Invalid checksum",
    "90": "Can not get merchant",
    "89": "UserId is required",
    "88": "Client no is required",
    "87": "MerchantId is required",
    "86": "TerminalId is required",
    "85": "Esb check user ekyc failed",
    "84": "Esb Insert ekyc account failed",
    "83": "Account otp is required",
    "82": "Esb confirm ekyc present failed",
    "81": "HDBS register user failed",
    "80": "Esb Update ekyc account failed",
    "79": "Token is required",
    "78": "Username is required",
    "77": " Password is required",
    "76": "Username or password incorrect",
    "75": "Ekyc type is required",
    "74": "Invalid ekyc type",
    "73": "Email is required",
    "72": "Account no is required",
    "71": "Phone number is required",
    "70": "Full name is required",
    "69": "Birth day is required",
    "68": "Full name ocr is required",
    "67": "Birth day ocr is required",
    "66": "Date of issue is required",
    "65": "Date of issue ocr is required",
    "64": "Place of issue is required",
    "63": "Place of issue ocr is required",
    "62": "Expired of issue is required",
    "61": "Expired of issue ocr is required",
    "60": "Gender is required",
    "59": "Address is required",
    "58": "Current address is required",
    "57": "Nationality is required",
    "56": "Branch is required",
    "55": "Marital status is required",
    "54": "Face matching is required",
    "53": "Id number is required",
    "52": "Id number type is required",
    "51": "Esb inquiry ekyc present failed",
    "50": "Invalid method",
    "49": "Invalid request",
    "41": "Invalid date of issue",
    "36": "Check HDBS account failed",
    "37": "Create HDBS account failed",
    "38": "Invalid expired of issue ocr",
    "39": "Invalid expired of issue",
    "40": "Invalid date of issue ocr",
    isUserImoney:
      "Your account cannot use the function. Please go to the counter to upgrade your account",
    userDontEnoughAccount:
      "Please open an online payment account or go to the counter to register for the service",
  },
};
